version: "3.5"
services:
  core_storit_db:
    platform: linux/amd64
    container_name: storit_db
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: storit
    ports:
      - "3340:3306"
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
