name: deploy

on:
  push:
    tags:
      - "**"

jobs:
  serverless:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - run: echo ${{ github.ref_name }}
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Export secret as env
        if: ${{ env.secret != 'null' }}
        run: echo "$secret" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
        env: 
          secret: ${{ toJson(secrets) }}
      - name: Export vars as env
        if: ${{ env.var != 'null' }}
        env:
          var: ${{ toJson(vars) }}
        run: echo "$var" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Serverless deploy
        uses: serverless/github-action@v3.1.0
        with:
          args: -c "serverless deploy --verbose --stage prod"
          entrypoint: /bin/sh
        env:
          NODE_OPTIONS: ${{ secrets.NODE_OPTIONS }}

